---
  - hosts: web
    connection: ssh
    become: True
    become_user: root
    roles:
      - role: robertdebock.keepalived
        keepalived_vrrp_instances:
          - name: VI_1
            state: MASTER
            interface: enp7s0
            unicast_src_ip: "10.9.96.68" 
            virtual_router_id: 51
            priority: 255
            authentication:
              auth_type: PASS
              auth_pass: "12345"
            virtual_ipaddresses:
              - name: "10.9.96.70/28"
        keepalived_vrrp_instances:
          - name: VI_2
            state: MASTER
            interface: enp6s0
            unicast_src_ip: "10.9.96.61" 
            virtual_router_id: 51
            priority: 255
            authentication:
              auth_type: PASS
              auth_pass: "12345"
            virtual_ipaddresses:
              - name: "10.9.96.37/27"