---
  - hosts: web
    connection: ssh
    become: True
    become_user: root  
    roles:
      - role: robertdebock.keepalived
        keepalived_vrrp_instances:
          - name: VI_1
            state: MASTER
            interface: eth0
            unicast_src_ip: "97.107.132.241" 
            virtual_router_id: 51
            priority: 110
            authentication:
              auth_type: PASS
              auth_pass: "12345"
            virtual_ipaddresses:
              - name: "244.135.50.180"
        keepalived_vrrp_instances:
          - name: VI_2
            state: MASTER
            interface: eth0
            unicast_src_ip: "66.175.210.70" 
            virtual_router_id: 51
            priority: 110
            authentication:
              auth_type: PASS
              auth_pass: "12345"
            virtual_ipaddresses:
              - name: "227.219.251.248"